spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://main30-diary.cs8oc5fuvzgl.ap-northeast-2.rds.amazonaws.com:13306/main?serverTimezone=Asia/Seoul
    username: admin
    password: admin-diary
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
    generate:
      ddl: true
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
      hibernate.SQL: debug
server:
  servlet:
    encoding:
      force-response: true
jwt:
  key: "j4nsK69sMIw67xksgHJoLXNwcmluZy1ib290LWp3dC10dXRvcmladsjkhz76HJFGukiy1209VHrKIOy7TDjr7420fgGFWnNO472CHhzbzZWNyZXQK"
  access-token-expiration-minutes: 10000
  refresh-token-expiration-minutes: 420
servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
