spring:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
    generate:
      ddl: true
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
      hibernate.SQL: debug
server:
  servlet:
    encoding:
      force-response: true

cloud:
  aws:
    s3:
      bucket: main30
    credentials:
      accessKey: "AKIASX4YIIHRXX274JCF"
      secretKey: "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"
    region:
      static: ap-northeast-2
    stack:
      auto: false